### ISSUE TITLE
Argument is missed in case chrono_literals 

### ISSUE THREAD

**Issue by Kurkin** [andreasfertig/cppinsights#15]
```
#include <chrono>
#include <string>

int main()
{
    using namespace std::literals;
    std::chrono::seconds t = 10s;
}
```
```
#include <chrono>
#include <string>

int main()
{
    using namespace std::literals;
    std::chrono::seconds t = std::operator""s();
}
```

**Comment by Kurkin** [comment]
Thanks for quick fix! Your tool is awesome!

**Comment by Kurkin** [comment]
Sorry, but as i can see test is failed and incorrect output generated
```
[FAILED] Issue15.cpp
32c32
<     std::chrono::seconds t = std::operator""s(98291919ull);
---
>     std::chrono::seconds t = std::operator""s<98291919>();
```

**Comment by andreasfertig** [comment]
Hi Kurkin,

I'm glad you like it.

Multiple things. Currently only the OS X tests count and should pass. The reason is, that libc++ and libstdc++ generate different results. As my main development happens under OS X I use that as a reference. The web front-end uses Docker and with that Linux. As far as I could see you reference the Linux build in the diff. Now the interesting thing seems to be that under Linux with libstdc++ it is in fact a template. So far it is correct. I'll have a separate look into why it does not compile.

**Comment by Kurkin** [comment]
I guess with libstdc++ it should be
```
    std::chrono::seconds t = std::operator""s<'9','8','2','9','1','9','1','9'>();
```
https://godbolt.org/g/ndb2yd

**Comment by andreasfertig** [comment]
Thanks that's it! Patch is on its way.
