### ISSUE TITLE
Anonymous struct shouldn't be named as `(anonymous)`

### ISSUE THREAD

**Issue by languagelawyer** [andreasfertig/cppinsights#290]
For the code below
```c++
union U {
  struct {} s;
};
```
[cppinsigths produces](https://cppinsights.io/lnk?code=dW5pb24gVSB7CiAgc3RydWN0IHt9IHM7Cn07&insightsOptions=cpp17&std=cpp17&rev=1.0)
```c++
struct U
{
  struct 
  {
  };
  
  struct (anonymous) s;
};

```

**Comment by andreasfertig** [comment]
Hello @languagelawyer,

thank you for your continuous support! That is in fact a little embarrassing, up to this point unions where not supported at all. They were shown as struct all the time.

The second thing which is wrong is the handling of anonymous structs, hence the `struct (anonymous) s;`. They are a bit harder to handle. In your example the resulting (down-stripped) AST is the following:

```
`-CXXRecordDecl 0x7fa84d82b620 <x.cpp:1:1, line:3:1> line:1:7 union U definition
  |-CXXRecordDecl 0x7fa84d82b760 <col:1, col:7> col:7 implicit union U
  |-CXXRecordDecl 0x7fa84d82b810 <line:2:3, col:11> col:3 struct definition
  `-FieldDecl 0x7fa84d82b9c0 <col:3, col:13> col:13 s 'struct (anonymous struct at x.cpp:2:3)':'U::(anonymous struct at x.cpp:2:3)'
```

The troublemaker is `CXXRecordDecl 0x7fa84d82b810 <line:2:3, col:11> col:3 struct definition` because it does not have a name. Ok it is anonymous. The `FieldDecl` afterwards is the declaration of `s`. So Clang does split the anonymous struct. Without a name it is impossible to declare the member `s`. My solution is to make up a name for the anonymous struct: `__anon_LINE_COL_`.

Andreas
