### ISSUE TITLE
Missing implicit cast for compound operator

### ISSUE THREAD

**Issue by mma666** [andreasfertig/cppinsights#405]
Hi @andreasfertig 

Thanks for creating great cppinsights! It's indeed so insightful! I noticed the operators doesn't expand for the built-in types like ```int``` and ```double```, while it works for ```complex``` type objects. Here is my code

```
#include <complex>
using namespace std;

int main () {
  
  int q = 2;
  ++q;
  q--;
  q += 2.0;
  
  complex<int> com1{3,4};
  complex<int> com2(com1);
  
  com1 += com2;
  com1 = com1 + com2;;
  
  return 0;
}
```

and here is what I get from cppinsights

```
#include <complex>
using namespace std;

int main()
{
  int q = 2;
  ++q;
  q--;
  q += 2.0;
  complex<int> com1 = std::complex<int>{3, 4};
  complex<int> com2 = std::complex<int>(static_cast<const std::complex<int>>(com1));
  com1.operator+=(static_cast<const std::complex<int>>(com2));
  com1.operator=(std::operator+(static_cast<const std::complex<int>>(com1), static_cast<const std::complex<int>>(com2)));
  ;
  return 0;
}
```

Also, I guess, in the case of  ```q += 2.0;``` the ```static_cast<int>``` is not shown. Are they real bugs?

Thank you.
Mehdi

**Comment by andreasfertig** [comment]
Hello @mma666,

you're welcome! Thanks for reporting issues!

Builtin types do not have operators. Only classes can have them.

The compound assignment is interesting. You're right, the cast is missing there. I checked it, and the fix is a bit more complicated, because the implicit cast is very implicit at this point. It is not part of the AST, as far as I can tell. I'm looking for a good way to provide a fix here, but it may take some time.

Best,

   Andreas

**Comment by mma666** [comment]
Hi @andreasfertig

Thanks for your reply. I learned something!

Best,
Mehdi
