### ISSUE TITLE
Capture lambda are missing the deleted copy assignment

### ISSUE THREAD

**Issue by Ignition** [andreasfertig/cppinsights#413]
I have no idea why the standard is this way....but it is.
Hence in cppinsights I would expect to see something like `__lambda_xyz& operator=(__lambda_xyz const &) = delete;` for lambdas that capture.  

http://eel.is/c++draft/expr.prim.lambda#closure-13

**Comment by andreasfertig** [comment]
Hello @Ignition,

that is an interesting point.

First let's be sure we are on the same page. You referring to something like this (in [C++ Insights](https://cppinsights.io/s/e896f12a))
:

```c++
int main()
{
  int a = 4;
  
  auto lamb = [a]{};
  decltype(lamb) lambCopy = lamb;
  // lamb = lambCopy;
}
```

The reason why you don't see the expected deleted assignment operator is simply because it is not there. Clang doesn't border creating implicit special members if they are not used. You can see this in the AST output at [Godbolt](https://godbolt.org/z/zov3oM6Mn). Once you start assigning the `lambCopy` to `lamb`, the assignment operator is used but then deleted, making the program ill-formed. As a result, you don't see any output in C++ Insights.

Andreas

**Comment by Ignition** [comment]
Yes, we are on the same page.

Ah yeah...if C++ insight is relying on Clang AST generation I see why ATM it says nothing on this topic.

Thank you for responding.
