### ISSUE TITLE
clang version error in Insights VSCode extension on Windows

### ISSUE THREAD

**Issue by ahmedshakill** [andreasfertig/cppinsights#422]
Trying to use insights vscode extension on windows .
I have added insights executable directory to path variable . 

Now I have VS 2019  and clang 11 installed .  But it gives this error .
I had clang 12 . Then switched to clang 11 but same error.
```
> Executing task: insights "f:\Code\python\Single Files\shared_ptr.cpp" > C:\Users\kingpin\AppData\Local\Temp\shared_ptr.cpp42748E73R7YC4qqBs.cpp <

Error while trying to load a compilation database:
Could not auto-detect compilation database for file "f:\Code\python\Single Files\shared_ptr.cpp"
No compilation database found in f:\Code\python\Single Files or any parent directory
fixed-compilation-database: Error while opening fixed database: no such file or directory
json-compilation-database: Error while opening JSON database: no such file or directory
Running without flags.
In file included from f:\Code\python\Single Files\shared_ptr.cpp:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\iostream:9:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\yvals_core.h:551:2: error: 
      STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.
#error STL1000: Unexpected compiler version, expected Clang 11.0.0 or newer.
 ^
1 error generated.
Error while processing f:\Code\python\Single Files\shared_ptr.cpp.
The terminal process "C:\WINDOWS\System32\cmd.exe /d /c insights "f:\Code\python\Single Files\shared_ptr.cpp" > C:\Users\kingpin\AppData\Local\Temp\shared_ptr.cpp42748E73R7YC4qqBs.cpp" terminated with exit code: 1.
```

**Comment by ki9gpin** [comment]
Could you elaborate and specify  "minimal working example"  ? I am not sure what you are asking 
IMO my system configuration for running "isights vscode extionsion"  is ok . 
I workspace directory contains  a  single  .cpp file . I was trying to run insights on that file using `command pallete -> show insights`  but it gives the error  as you can see .

**Comment by andreasfertig** [comment]
Hello @ki9gpin,

sorry I was not precise. I'm talking about ta small code snipped that leads to the error.

Andreas

**Comment by andreasfertig** [comment]
Hello @ki9gpin,

thank you!

A look at [`yvals_core.h`](https://github.com/microsoft/STL/blob/88332706f49d3297b200b5605ef174fc47d38d1a/stl/inc/yvals_core.h#L593) shows a compiler version matching for the STL version going on.

Can you try to set the define `_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH`  in the build-flags? This [article](https://devblogs.microsoft.com/cppblog/c17-progress-in-vs-2017-15-5-and-15-6/) says that it can be an escape hatch.

Switching your Clang version probably doesn't matter because I assume that the Clang version the error refers to is the Clang version C++ Insights was build with. That should be 12. Do you have the latest binary installed? 

Andreas
