### ISSUE TITLE
Structured bindings with pair/tuple not producing references

### ISSUE THREAD

**Issue by vittorioromeo** [andreasfertig/cppinsights#425]
The following code:

```cpp
#include <utility>

int main()
{
    std::pair<int, char> p;
  	auto [a, b] = p;
}
```

Produces this after being run in cppinsights:

```cpp
#include <utility>

int main()
{
  std::pair<int, char> p = std::pair<int, char>();
  std::pair<int, char> __p6 = std::pair<int, char>(p);
  int a = std::get<0UL>(static_cast<std::pair<int, char> &&>(__p6));
  char b = std::get<1UL>(static_cast<std::pair<int, char> &&>(__p6));
}
```

I think that is incorrect. It should be:

Produces this after being run in cppinsights:

```cpp
#include <utility>

int main()
{
  std::pair<int, char> p = std::pair<int, char>();
  std::pair<int, char> __p6 = std::pair<int, char>(p);
  int& a = std::get<0UL>(static_cast<std::pair<int, char> &&>(__p6));
  char& b = std::get<1UL>(static_cast<std::pair<int, char> &&>(__p6));
}
```

According to cppreference:

> For each identifier, a variable whose type is "reference to std::tuple_element<i, E>::type" is introduced: [...]

**Comment by andreasfertig** [comment]
Hello @vittorioromeo,

thanks for reporting this. I took me some time but I think I figured the correct behavior out. The patch will contain additional information, but I will explain it here as well for documentation purposes and discussions.

I agree that what C++ Insights showed was wrong. However, the resulting code should be

```C++
  std::pair<int, char> p = std::pair<int, char>();
  std::pair<int, char> __p6 = std::pair<int, char>(p);
  int&& a = std::get<0UL>(static_cast<std::pair<int, char> &&>(__p6));
  char&& b = std::get<1UL>(static_cast<std::pair<int, char> &&>(__p6));
```

Both `a` and `b` are rvalue reference because `get` is called with an rvalue of `__p6`. That is also what the quote from cppreference describes. The text there seems to agree what the standard says in [eel.is/c++draft/dcl.struct.bind#4](https://eel.is/c++draft/dcl.struct.bind#4).


Andreas
