### ISSUE TITLE
C++20 lambda in unevaluated context not shown

### ISSUE THREAD

**Issue by andreasfertig** [andreasfertig/cppinsights#468]
This is a copy from 467 from @JJCuber, to track the issues individually.

Andreas

----

I just wanted to add that I've noticed a few other oddities when it comes to lambdas, including this (for C++20):
```cpp
template<class F = decltype([]() { return true; })>
bool test(F f = {})
{
  return f();
}

int main()
{
  test();
}
```
generates
```cpp
template<class F = decltype([]() { return true; })>
bool test(F f = {})
{
  return f();
}

/* First instantiated from: insights.cpp:9 */
#ifdef INSIGHTS_USE_TEMPLATE
template<>
bool test<__lambda_1_29>(__lambda_1_29 f)
{
  return f.operator()();
}
#endif


int main()
{
  test(__lambda_1_29{});
  return 0;
}
```
(It uses a class that was never declared/defined.)

**Comment by JJCUBER** [comment]
The code still seems to fail to generate the lambda class unless the function is wrapped in a namespace/struct/class.  Most of the `p0315` tests seem to wrap the places where lambdas are in unevaluated contexts in a namespace/struct/class, so maybe this was intentional and/or a limitation?

I just wanted to bring attention to this just in case it was not intentional.

**Comment by andreasfertig** [comment]
Hello @JJCUBER,

thanks for verifying! The matchers are the troublemakers. You spotted the missing case for the primary function template. A few commits ago, I refactored the matchers, enabling the upcoming patch to fix this issue.

Andreas
