### ISSUE TITLE
make command issue

### ISSUE THREAD

**Issue by akashreddy1** [andreasfertig/cppinsights#498]
I have rum the docker file(- https://github.com/andreasfertig/cppinsights-docker-base/blob/46dca0cf729dbeb558ffdf7208da1fc6c186586e/Dockerfile#L11) using make command and I am getting error below,
![Screenshot from 2022-08-12 02-56-13](https://user-images.githubusercontent.com/111112614/184331519-00651e15-c74a-4f36-a682-bb573b52d793.png)
I want to be install cpp insights in ubuntu 20.04 and get the template instantiation in my ubuntu 20.04,
please help me, which method can I follow.
Thank you.

**Comment by andreasfertig** [comment]
Hello @akashreddy1,

I moved this issue to the correct repository: https://github.com/andreasfertig/cppinsights/issues/498

**Comment by andreasfertig** [comment]
Hello @akashreddy1,

I pointed you to the Docker file in our email conversation since you asked me which packages to install. I'm still not sure what you're trying to accomplish. Your native Ubuntu, you say, is 20.04, but the Docker container will use 21.04. It would be great if you could clarify what you are trying to accomplish.

The Docker build above fails with an HTTPS connection error where it says connection refused while trying to fetch the LLVM package information. Most likely, this is related to your local setup.

For building C++ Insights, a description is here: https://github.com/andreasfertig/cppinsights#building-outside-clang

You need the LLVM/Clang binaries in your shell path so that CMake can find llvm-config. The Docker file shows which packages you need for 21.04. Probably the same are required for 20.04.

The rest then is executing CMake as it is described in the Readme.

Combining the two sources, for at least Ubuntu 21.04 the commands are the following:

```
echo "deb http://apt.llvm.org/${UBUNTU_NAME}/ llvm-toolchain-${UBUNTU_NAME}-${CLANG_VERSION} main" >> /etc/apt/sources.list
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
apt-get update && apt-get install -y --no-install-recommends libstdc++-${GCC_VERSION}-dev libc++-${CLANG_VERSION}-dev libclang-${CLANG_VERSION}-dev
git clone https://github.com/andreasfertig/cppinsights.git
mkdir build && cd build
cmake -G"Ninja" ../cppinsights
ninja
```

At the time of writing this, C++ Insights uses CLANG_VERSION 14, GCC_VERSION 11, and UBUNTU_NAME hirsute, as the Docker file shows. The first two commands most likely require sudo. LLVM shows an alternative to the first three steps in the "Automatic installation script" section: https://apt.llvm.org/ However, this way installs more packages than C++ Insights needs.

Please understand that I do not provide step-by-step instructions as there are simply too many distributions. But feel free to add your steps to the Readme and send me a PR.


Andreas

**Comment by akashreddy1** [comment]
can you please send the docker commends for ubuntu 20.04.
I am trying to install cpp insights in ubuntu 20.04 and I have gcc-11 installed in ubuntu 20.04.
I want to get the template instantiation output for simple example and I want to store the result to output file.

**Comment by akashreddy1** [comment]
Also I am trying to install cpp insights in ubuntu 20.04 using following commands
git clone https://github.com/andreasfertig/cppinsights.git
mkdir build && cd build
cmake -G"Ninja" ../cppinsights
ninja

After this "git clone https://github.com/andreasfertig/cppinsights.git" command I have changed the Cmake in line number 13 to
set(INSIGHTS_LLVM_CONFIG "llvm-config-14" CACHE STRING "LLVM config 14 executable to use") because after running this command it is giving error like llvm-config not found. I have llvm-config-14 installed so it is searching for only llvm-config.
After changing line number 13 to llvm-config-14, the command run successfully.
After that I have run ninja command
![Screenshot from 2022-09-04 22-29-11](https://user-images.githubusercontent.com/111112614/188368025-03474c95-b468-4bc3-bd0a-9be3d67692bb.png)
It is giving above output.
I have tried this insights file1.cpp -- -std=c++17 command with one example file but it is giving error like command not found

**Comment by andreasfertig** [comment]
Hello @akashreddy1,

while I'm still confused about the two different options you consider here (Docker or local build), the output looks to me like you've succeeded. I'm guessing since "`insights`" is not in a search-path of your shell, you need to put "`./`" in front when you invoke the binary: 

```
./insights file.cpp -- -st=c++17
```

Andreas
