### ISSUE TITLE
Error building inside clang source tree

### ISSUE THREAD

**Issue by GKxxQAQ** [andreasfertig/cppinsights#554]
I followed [this page](https://clang.llvm.org/get_started.html) (Building Clang and Working with the Code, On Unix-like Systems) to download and build the clang source tree. The source tree looks just like [this one](https://codebrowser.dev/llvm/). When building cppinsights inside clang (as mentioned in `Readme.md`) I encountered the following problems:

1. The path `llvm/tools/clang/tools/extra` does not exist. `find . -name extra` gives only `./llvm/test/tools/llvm-cov/Inputs/sources_specified/extra`. I found the directory called `clang-tools-extra` which seems to be the right place since it contains other tools like `clang-tidy` and `clang-query`. Then I cloned `cppinsights` here and added `add_subdirectory(cppinsights)` into `clang-tools-extra/CMakeLists.txt`.
2. `cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -G "Unix Makefiles" ../llvm` gives the following error:
```cmake
CMake Error at cmake/modules/LLVM-Config.cmake:106 (get_target_property):
  get_target_property() called with non-existent target "LLVM_INCLUDE_DIR".
Call Stack (most recent call first):
  cmake/modules/LLVM-Config.cmake:98 (explicit_llvm_config)
  /home/gkxx/install/llvm-project/clang-tools-extra/cppinsights/CMakeLists.txt:442 (llvm_config)
```

I have no idea how to fix this.

**Comment by andreasfertig** [comment]
Hello @GKxxQAQ,

I haven't done an in-source-tree build for a very long time. As far as I can tell, you're correct. LLVM did a restructuring moving all tools into `clang-tools-extra`. The steps you've made look correct to me. I assume that the C++ Insights cmake file needs an update due to the new directory structure. It might take a while for me to find time to look into this as I usually compile C++ Insights with a pre-built LLVM to save time.

It might be that looking at, for example, clang-tidy's cmake file might hint at how to find the `LLVM_INCLUDE_DIR` or what else has to be done now.

Andreas
