### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [andreasfertig/cppinsights#592]
👋 not sure if the release scheme got changed, but it looks like the latest tag is `v_16.0` rather than `v_0.10`.

relates to https://github.com/Homebrew/homebrew-core/pull/150239

**Comment by andreasfertig** [comment]
Hello @chenrui333,

thanks for asking! Yes, I forgot to mention that in my blog post. Since the version number never meant much, I decided to use the same major number as the LLVM/Clang version that C++ Insights supports. That way, from the C++ Insights version number, one can know which LLVM/Clang version is required for building from the source.

Thanks for creating the Homebrew package! This was on my to-do list for a long time.

Andreas
