### ISSUE TITLE
different result from godbolt

### ISSUE THREAD

**Issue by organicoman** [andreasfertig/cppinsights#604]
[https://godbolt.org/z/8voTfe1Y1](url)

**Comment by andreasfertig** [comment]
Hello @organicoman,

thanks for opening an issue. I like chasing bugs. I like chasing what the bug is less. From your short issue description, I can only guess. Here is my guess.

You noticed that the code you linked compiles on Godbolt but is rejected with a compiler error on cppinsights.io. The link you provided to CE uses gcc as a compiler. However, C++ Insights is a Clang-based tool. Switching the CE compiler to Clang also results in a compiler error on Godbolt. 

Based on my guess, this is not a C++ Insights issue. I hope I guessed right and this helps. 

Andreas
