### ISSUE TITLE
Generated function specializations: Parameters generated from parameter packs use the same name

### ISSUE THREAD

**Issue by neobrain** [andreasfertig/cppinsights#62]
C++ Insights generates explicit specializations for template functions. When the primary function template contains any parameter packs, the parameters generated from the pack in the specialization will all use the same name. It would be nice for the names to be distinguished.

See below:

<table>
<tr>
<th>
Input
</th>
<th>
C++ Insights
</th>
<th>
Desired
</th>
</tr>
<tr>
<td  valign="top">
<pre lang="cpp">
template&lt;typename... T&gt;
int func(T... t) {
    return func(t...);
}

int _ = func(5, 5);
</pre>
</td>
<td  valign="top">
<pre lang="cpp">
#ifdef USE_TEMPLATE
template&lt;&gt;
int func&lt;int, int&gt;(int t, int t)
{
  return func(t, t);
}
#endif

int _ = func(5, 5);
</pre>
</td>
<td  valign="top">
<pre lang="cpp">
#ifdef USE_TEMPLATE
template&lt;&gt;
int func&lt;int, int&gt;(int t1, int t2)
{
  return func(t1, t2);
}
#endif

int _ = func(5, 5);
</pre>
</td>
</tr>
</table>

Fixing this requires C++ Insights to detect which ParmVarDecls in a specialized FunctionDecl correspond to parameter packs in the primary function template (and then just suffix them with a counter, for instance). Annoyingly, I haven't found a good way in libclang to do so other than traversing all primary function template parameters and comparing them by name to the current ParmVarDecl :/

**Comment by andreasfertig** [comment]
Hi Tony,

thanks for the report. I know this problem and unfortunately I haven't found a good solution, because as you mention libclang does not provide a way to retrieve the name. I once played with the idea of a counter but did not succeed. I just don't remember why. I believe it was because at the time the parameter name is generated, there is no more knowledge whether it is for a parameter pack.

A patch is welcome :-)
