### ISSUE TITLE
coroutines TS

### ISSUE THREAD

**Issue by Trass3r** [andreasfertig/cppinsights#92]
Would be useful to see the implemented state machine if that's possible.
https://godbolt.org/z/q6rOaN

**Comment by andreasfertig** [comment]
Hello Trass3r,

I agree. Funny thing, just yesterday I thought about this. I will have a look and see what I can do here.

**Comment by Trass3r** [comment]
A bit like https://youtu.be/ZTqHjjm86Bw?t=27m11s

**Comment by andreasfertig** [comment]
Sorry, I'm testing stale bot and it does exactly the opposite of what I want. This issue will remain open.

**Comment by grishavanika** [comment]
Hi. @andreasfertig :)

Is there any progress with this ? Is it possible to contribute ? (nothing to show yet, just asking)

**Comment by andreasfertig** [comment]
Hello @grishavanika,

thanks for asking. Currently, I'm busy with a larger rewrite to transform even more code and to support generic lambdas. I have a private branch where I made some progress with coroutines. As they are now officially part of C++20 things are a bit easier (no additional option is required to activate them).

Examples of coroutines and how the transformed code looks like would help me. In general, I'm not sure how this transformation turns out and if it is helpful at all. However, I plan to approach some people more familiar with coroutines.

All that said, if you like to jump in I can push my development branch or you start something of your own.

Andreas

**Comment by Trass3r** [comment]
See https://github.com/andreasfertig/cppinsights/issues/92#issuecomment-443391350

**Comment by andreasfertig** [comment]
Hello @Trass3r,

I know that, thanks. I just like more data. Plus some things are not 100% clear to me. But, I have to check the branch, its been a while since I made changes to it. I will push it and let you know.

Andreas

**Comment by andreasfertig** [comment]
Hello all,

I just pushed my draft development branch. The entire branch is more or less just to show what new statements are available and tries to format them.

I'm not clear on:
- when and how a coroutine is allocated and how to visualize that.
- how to visualize the suspend and resume 

Probably there are more things, but that is what I remember so far. Feel free to contribute.


Andreas

**Comment by andreasfertig** [comment]
Hello,

I wrote up a blog post about implementing coroutines in C++ Insights. There are quite some bummers. You can find it here [andreasfertig.blog/2019/09/coroutines-in-c-insights.html](http://bit.ly/2mAd5FI). In addition to decide what to do I set up a Twitter poll you can [take](https://twitter.com/Andreas__Fertig/status/1178940510569996288?s=20).

Andreas
